### ISSUE TITLE
getting error on use

### ISSUE THREAD

**Issue by KyleDavidE** [erossignon/node-occ#12]
When I try and run the example or anything that uses the library I get the following error

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libTKBO.so.7: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (PROJECT ROOT/node_modules/node-occ/lib/bindings.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by adamjcook** [comment]
Try running the following command, before running the mocha tests.

`sudo ldconfig`

Also, make sure that you run `sudo make install` after you compile the sources.

Tested on Ubuntu LTS 14.04 x84-64.
