### ISSUE TITLE
Build error in node-gyp build

### ISSUE THREAD

**Issue by skbizport** [erossignon/node-occ#15]
Hi,

I am trying to build node-occ on ubuntu and get following error during node-gyp build command. Any help is appreciated.

/usr/local/include/oce/TCollection_Sequence.lxx:31:8: note: in expansion of macro ‘TCollection_Sequence’
 inline TCollection_Sequence::TCollection_Sequence(const TCollection_Sequence& theOther)
        ^
../src/ShapeFactory.cc: At global scope:
../src/ShapeFactory.cc:12:8: error: ‘Primitives_Direction’ was not declared in this scope
 char m(Primitives_Direction p)
        ^
../src/ShapeFactory.cc:13:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
make: *** [Release/obj.target/occ/src/ShapeFactory.o] Error 1

**Comment by erossignon** [comment]
Make sure that you build node-occ with OCE version 0.13 , this is the version currently supported
As you are running Ubuntu, you should be able to use the prepare.sh script to build OCE from source.

````sh
git clone https://github.com/erossignon/node-occ
cd node-occ
prepare_build.sh
npm install

````

**Comment by skbizport** [comment]
Initially i  was using 0.17. Reverted back to 0.13. 
Now I am able to complete the build process. Thx for the tip.
However now getting following error when running tests or sample:
-----------------------------------------------------------------------------------------------------------------------

~/dev/occ/node-occ$ mocha
adding occ.Mesh.prototype.toJSON function

/home/username/dev/occ/node-occ/lib/occ.js:26
  var solid = occ.makeBox([10,20,30],[40,50,60]);
                  ^
Error: cannot build box
    at /home/username/dev/occ/node-occ/lib/occ.js:26:19
    at Object.<anonymous> (/home/usename/dev/occ/node-occ/lib/occ.js:29:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/shaileshk/dev/occ/node-occ/lib/shapeFactory.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/shaileshk/dev/occ/node-occ/test/test_BREP.js:3:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/lib/node_modules/mocha/lib/mocha.js:187:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/lib/node_modules/mocha/lib/mocha.js:184:14)
    at Mocha.run (/usr/lib/node_modules/mocha/lib/mocha.js:405:31)
    at Object.<anonymous> (/usr/lib/node_modules/mocha/bin/_mocha:405:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by skbizport** [comment]
Using Node version v0.10.33.

**Comment by skbizport** [comment]
node-gyp rebuild did the trick.

Thx for creating this extension.
